title: "if __name__ == 'alexandra':"
author: Alexandra
description: >-
  a blog that is probably about software development but like yeah nah
baseurl: ""
url: "alexandrabaier.github.io"
github_username: AlexandraBaier
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
  syntax_highlighter: none
theme: null
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - .bundle
  - README.md
